version: '3.3'

services:

 postgres-13:
    image: postgres:13
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: nyc_data
    volumes:
      - "./postgres-init.sh:/docker-entrypoint-initdb.d/postgres-init.sh"